name: Model Architecture Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'Session5/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Session5/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision pytest

      - name: Run architecture tests
        working-directory: ./Session5
        run: |
          pytest test_model.py -v
